server:
  port: 8080
  address: 0.0.0.0
spring:
  profiles:
    active: dev
  datasource:
#    url: jdbc:mysql://192.168.2.6:3306/aiflowy?useInformationSchema=true&characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/aiflowy?useInformationSchema=true&characterEncoding=utf-8
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/public
  mvc:
    static-path-pattern: /static/**
aiflowy:
  storage:
    local:
      root: ''
  ollama:
    host: http://127.0.0.1:11434
  login:
    excludes: /api/v1/auth/**, /static/**